<a href="https://colab.research.google.com/github/Sara2004011/Progetto-Python-/blob/main/progetto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import kagglehub
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.3f}'.format)
sns.set_theme(style='whitegrid', palette='muted')
plt.rcParams['figure.figsize'] = (12, 5)

print('Librerie importate correttamente')

Librerie importate correttamente

In [2]:
DATASET_ID = "guriya79/mental-health-disorder"
FILE_NAME  = "mental_health_risk_dataset (1).csv"
OUTPUT_DIR = os.path.join(os.getcwd(), "data", "mental_health")

# 2. Download del dataset
kagglehub.dataset_download(DATASET_ID, output_dir=OUTPUT_DIR)

# 3. Caricamento del dataset in un DataFrame Pandas
# Usiamo os.path.join per unire il percorso della cartella e il nome del file
df = pd.read_csv(os.path.join(OUTPUT_DIR, FILE_NAME))

# 4. Verifica del caricamento
print(f'Dataset "Mental Health" caricato correttamente!')
print(f'Dimensioni: {df.shape[0]:,} righe × {df.shape[1]} colonne')

# Mostra le prime 5 righe per vedere i dati
df.head()

Downloading to /content/data/mental_health/1.archive...

100%|██████████| 517k/517k [00:00<00:00, 73.0MB/s]

Extracting files...
Dataset "Mental Health" caricato correttamente!
Dimensioni: 25,000 righe × 25 colonne

,age,gender,marital_status,education_level,employment_status,sleep_hours,physical_activity_hours_per_week,screen_time_hours_per_day,social_support_score,work_stress_level,academic_pressure_level,job_satisfaction_score,financial_stress_level,working_hours_per_week,anxiety_score,depression_score,stress_level,mood_swings_frequency,concentration_difficulty_level,panic_attack_history,family_history_mental_illness,previous_mental_health_diagnosis,therapy_history,substance_use,mental_health_risk
0,56,Other,Single,Bachelor,Unemployed,8.600,2.800,9.600,7,10,3,7,8,40,5,4,8,8,3,1,0,1,1,1,1
1,47,Male,Single,Bachelor,Unemployed,4.500,2.700,3.000,10,6,9,1,10,31,3,7,4,9,3,0,0,0,0,0,0
2,56,Female,Divorced,Bachelor,Student,3.100,14.100,7.200,10,5,2,4,7,28,8,3,1,4,2,1,1,1,1,1,2
3,59,Other,Married,Bachelor,Employed,7.000,0.500,10.300,2,10,4,8,7,63,9,8,5,2,5,1,1,0,1,1,2
4,58,Male,Single,High School,Self-Employed,5.100,2.500,1.200,8,1,8,8,3,28,1,8,3,3,1,0,0,1,0,1,0

In [6]:
print("--- Informazioni Generali ---")
df.info()
print("--- Analisi Descrittive ---")
df.describe().T.style \
    .background_gradient(cmap='Blues', subset=['mean', 'std']) \
    .highlight_min('mean', color='lightcoral')

--- Informazioni Generali ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 25 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   age                               25000 non-null  int64
 1   gender                            25000 non-null  object
 2   marital_status                    25000 non-null  object
 3   education_level                   25000 non-null  object
 4   employment_status                 25000 non-null  object
 5   sleep_hours                       25000 non-null  float64
 6   physical_activity_hours_per_week  25000 non-null  float64
 7   screen_time_hours_per_day         25000 non-null  float64
 8   social_support_score              25000 non-null  int64
 9   work_stress_level                 25000 non-null  int64
 10  academic_pressure_level           25000 non-null  int64
 11  job_satisfaction_score            25000 non-null  int64
 12  financial_stress_level            25000 non-null  int64
 13  working_hours_per_week            25000 non-null  int64
 14  anxiety_score                     25000 non-null  int64
 15  depression_score                  25000 non-null  int64
 16  stress_level                      25000 non-null  int64
 17  mood_swings_frequency             25000 non-null  int64
 18  concentration_difficulty_level    25000 non-null  int64
 19  panic_attack_history              25000 non-null  int64
 20  family_history_mental_illness     25000 non-null  int64
 21  previous_mental_health_diagnosis  25000 non-null  int64
 22  therapy_history                   25000 non-null  int64
 23  substance_use                     25000 non-null  int64
 24  mental_health_risk                25000 non-null  int64
dtypes: float64(3), int64(18), object(4)
memory usage: 4.8+ MB
--- Analisi Descrittive ---

In [9]:
missing = pd.DataFrame({
    'count': df.isnull().sum(),
    'percent': df.isnull().mean() * 100
})

if missing.empty:
    print('Nessun valore mancante nel dataset!')
else:
    print(f'{len(missing)} colonne con valori mancanti:')
    display(missing.style.bar(subset=['percent'], color='#d65f5f'))

Nessun valore mancante nel dataset!